name: Helm Publish

env:
    IMAGE_NAME: cert-manager-webhook-wedos
    IMAGE_TAG: ${{ github.sha }}
    IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Push to Registry action
        uses: actions/checkout@v4

      - name: lowercase image name
        run: |
          echo "IMAGE=`echo ${IMAGE_REGISTRY}/${IMAGE_NAME} | tr '[:upper:]' '[:lower:]'`" >>${GITHUB_ENV}

      - name: Build Image
        run: |
          docker build . --file Dockerfile --tag $IMAGE:${IMAGE_TAG} 
          docker tag $IMAGE:${IMAGE_TAG} $IMAGE:latest

      - name: Push Docker image
        run: |
          docker push $IMAGE:${IMAGE_TAG}
          docker push $IMAGE:latest

  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Push to Registry action
        uses: actions/checkout@v4

      - uses: J12934/helm-gh-pages-action@master
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
